// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjOgNRpzM-Wm_f9n1E2pC2Zzufx_r8LXU',
    appId: '1:85627459753:web:8bc3d79143e17e2327f1b8',
    messagingSenderId: '85627459753',
    projectId: 'guardloco',
    authDomain: 'guardloco.firebaseapp.com',
    storageBucket: 'guardloco.firebasestorage.app',
    measurementId: 'G-DTBFP9WN1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB2yGDSd3lEeg4ZxtlgPWi3bp-DqKDCF0',
    appId: '1:85627459753:android:8de845e8488c97f827f1b8',
    messagingSenderId: '85627459753',
    projectId: 'guardloco',
    storageBucket: 'guardloco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYQPzZU4PDCsHOVgDY7vDGE4XOmYdkFA',
    appId: '1:85627459753:ios:5125eb7a792a2f5927f1b8',
    messagingSenderId: '85627459753',
    projectId: 'guardloco',
    storageBucket: 'guardloco.firebasestorage.app',
    iosBundleId: 'com.guardloco.carguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYQPzZU4PDCsHOVgDY7vDGE4XOmYdkFA',
    appId: '1:85627459753:ios:5125eb7a792a2f5927f1b8',
    messagingSenderId: '85627459753',
    projectId: 'guardloco',
    storageBucket: 'guardloco.firebasestorage.app',
    iosBundleId: 'com.guardloco.carguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjOgNRpzM-Wm_f9n1E2pC2Zzufx_r8LXU',
    appId: '1:85627459753:web:8bc3d79143e17e2327f1b8',
    messagingSenderId: '85627459753',
    projectId: 'guardloco',
    authDomain: 'guardloco.firebaseapp.com',
    storageBucket: 'guardloco.firebasestorage.app',
    measurementId: 'G-DTBFP9WN1E',
  );

}