"""initial schema

Revision ID: b2c0707d9e5a
Revises: 
Create Date: 2026-04-07 16:32:02.291084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c0707d9e5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('night_vision', sa.Boolean(), nullable=False),
    sa.Column('webrtc_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_motion', sa.Boolean(), nullable=False),
    sa.Column('alert_impact', sa.Boolean(), nullable=False),
    sa.Column('alert_sound', sa.Boolean(), nullable=False),
    sa.Column('alert_proximity', sa.Boolean(), nullable=False),
    sa.Column('local_storage', sa.Boolean(), nullable=False),
    sa.Column('cloud_sync', sa.Boolean(), nullable=False),
    sa.Column('auto_delete', sa.Boolean(), nullable=False),
    sa.Column('clip_length', sa.Integer(), nullable=False),
    sa.Column('encryption', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_armed', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('firmware_version', sa.String(), nullable=False),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('mcu_temp_c', sa.Float(), nullable=False),
    sa.Column('wifi_rssi', sa.Integer(), nullable=False),
    sa.Column('storage_total_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_used_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_video_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_logs_bytes', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vibration_g', sa.Float(), nullable=False),
    sa.Column('motion_detected', sa.Boolean(), nullable=False),
    sa.Column('ultrasonic_meters', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('wifi_rssi', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_logs_timestamp'), 'sensor_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webrtc_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sdp_offer', sa.Text(), nullable=True),
    sa.Column('sdp_answer', sa.Text(), nullable=True),
    sa.Column('ice_candidates', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_clips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('motion', 'impact', 'sound', 'proximity', 'scheduled', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('is_cloud_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_clips_timestamp'), 'video_clips', ['timestamp'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('motion', 'impact', 'sound', 'proximity', 'scheduled', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('clip_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['video_clips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_video_clips_timestamp'), table_name='video_clips')
    op.drop_table('video_clips')
    op.drop_table('webrtc_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensor_logs_timestamp'), table_name='sensor_logs')
    op.drop_table('sensor_logs')
    op.drop_table('device_status')
    op.drop_table('device_settings')
    # ### end Alembic commands ###
